name: Rebase Upstream
on:
  schedule:
    - cron: "30 4 * * WED"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: imba-tjd/rebase-upstream-action@master

